[ClassVersion("1.0.0.0"), FriendlyName("GroupPolicyAssignment")]
class MSFT_GroupPolicyAssignment : OMI_BaseResource
{
    [Required, Description("Name of the GPO policy to create")] String GPOName;

    [Required, Description("OU to assign GPO to")] String OUPath;

    [Description("Flag to indicate whether the policy is enforced")] String Enforced;

    [Description("Flag to indicate whether the policy is linked")] String LinkEnabled = "Yes";
    
    [Write, Description("Desired state of resource."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
