#
# Module manifest for module 'GroupPolicyDSC'
#
# Generated by: Stanislaw Wozniak
#
# Generated on: 01/12/2021
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
moduleVersion = '1.0.0.0'

# ID used to uniquely identify this module
GUID = '14bbc382-0b5e-4a36-8b73-f23287456264'

# Author of this module
Author = 'Stanislaw Wozniak'

# Company or vendor of this module
CompanyName = 'Evops Limited'

# Copyright statement for this module
Copyright = '(c) 2021 Evops Limited. All rights reserved.'

# Description of the functionality provided by this module
Description = 'The GroupPolicyDSC module allows you to configure and manage GPO policies on the domain controller.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
# FunctionsToExport = '*'

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @( 'DSC','DesiredStateConfiguration','DSCResourceKit','DSCResource','AuditPolicy', 'GroupPolicy' )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/eu-evops/GroupPolicyDSC/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/eu-evops/GroupPolicyDSC'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Explicitly removed extra hidden files from release package

'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}




